#!/bin/bash
#SBATCH --time=00:30:00
#SBATCH --cpus-per-task=2
#SBATCH --mem=4G
#SBATCH --array=0-167
#SBATCH --job-name=03a_eq
#SBATCH --partition=standard
#SBATCH --account=YOUR_ACCOUNT_NAME
#SBATCH --output=_logs/03a_eq_%A_%a.log

# 03a_equalize.sh — SLURM array: symlink or subsample each BAM.
#
# Reads _logs/03a_jobs.tsv (generated by 03a_make_eq_jobs.py).
# For symlinks, also symlinks the .bai index.
#
# Usage:
#     python 03a_make_eq_jobs.py   # generates job table
#     sbatch 03a_equalize.sh       # 168-task array


JOBS_TSV=_logs/03a_jobs.tsv
if [ ! -f "$JOBS_TSV" ]; then
    echo "[ERROR] $JOBS_TSV not found. Run 03a_make_eq_jobs.py first." >&2
    exit 1
fi

# +2: skip header, 0-based task ID
LINE=$((SLURM_ARRAY_TASK_ID + 2))
ROW=$(sed -n "${LINE}p" "$JOBS_TSV")
if [ -z "$ROW" ]; then
    echo "[ERROR] empty row at line $LINE in $JOBS_TSV" >&2
    exit 1
fi

INPUT_BAM=$(echo "$ROW" | cut -f1)
OUTPUT_BAM=$(echo "$ROW" | cut -f2)
ACTION=$(echo "$ROW" | cut -f3)
SEED_FRAC=$(echo "$ROW" | cut -f4)

echo "[task ${SLURM_ARRAY_TASK_ID}] action=$ACTION"
echo "[task ${SLURM_ARRAY_TASK_ID}] input:  $INPUT_BAM"
echo "[task ${SLURM_ARRAY_TASK_ID}] output: $OUTPUT_BAM"

# Create output directory
mkdir -p "$(dirname "$OUTPUT_BAM")"

if [ "$ACTION" = "symlink" ]; then
    # Symlink BAM and .bai
    ln -sf "$INPUT_BAM" "$OUTPUT_BAM"
    if [ -f "${INPUT_BAM}.bai" ]; then
        ln -sf "${INPUT_BAM}.bai" "${OUTPUT_BAM}.bai"
    elif [ -f "${INPUT_BAM%.bam}.bai" ]; then
        ln -sf "${INPUT_BAM%.bam}.bai" "${OUTPUT_BAM}.bai"
    fi
    echo "[OK] symlinked $OUTPUT_BAM"

elif [ "$ACTION" = "subsample" ]; then
    echo "[INFO] subsampling with seed.fraction=$SEED_FRAC"
    samtools view -b -s "$SEED_FRAC" "$INPUT_BAM" > "$OUTPUT_BAM"
    samtools index "$OUTPUT_BAM"
    NREADS=$(samtools view -c "$OUTPUT_BAM")
    echo "[OK] subsampled $OUTPUT_BAM ($NREADS reads)"

else
    echo "[ERROR] unknown action: $ACTION" >&2
    exit 1
fi
