#!/bin/bash
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --array=0-167
#SBATCH --job-name=04b_frag
#SBATCH --partition=standard
#SBATCH --account=YOUR_ACCOUNT_NAME
#SBATCH --output=_logs/04b_frag_%A_%a.log

# 04b_bam_to_frags.sh — SLURM array: BAM → name-sort → fragment extraction.
#
# Reads _logs/04b_jobs.tsv (generated by 04b_make_fp_jobs.py).
#
# Usage:
#     python 04b_make_fp_jobs.py
#     sbatch 04b_bam_to_frags.sh

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

JOBS_TSV=_logs/04b_jobs.tsv
if [ ! -f "$JOBS_TSV" ]; then
    echo "[ERROR] $JOBS_TSV not found. Run 04b_make_fp_jobs.py first." >&2
    exit 1
fi

CPUS=${SLURM_CPUS_PER_TASK:-8}

# +2: skip header, 0-based task ID
LINE=$((SLURM_ARRAY_TASK_ID + 2))
ROW=$(sed -n "${LINE}p" "$JOBS_TSV")
if [ -z "$ROW" ]; then
    echo "[ERROR] empty row at line $LINE" >&2
    exit 1
fi

EQ_BAM=$(echo "$ROW" | cut -f5)
FRAG_OUT=$(echo "$ROW" | cut -f6)
SAMPLE_ID=$(echo "$ROW" | cut -f4)

echo "[task ${SLURM_ARRAY_TASK_ID}] sample=$SAMPLE_ID"
echo "[task ${SLURM_ARRAY_TASK_ID}] bam=$EQ_BAM"
echo "[task ${SLURM_ARRAY_TASK_ID}] frag=$FRAG_OUT"

# Resolve symlink to actual BAM (samtools sort needs the real file)
REAL_BAM=$(readlink -f "$EQ_BAM")

# Create output directory
mkdir -p "$(dirname "$FRAG_OUT")"

# Temp name-sorted BAM (in the same dir as output to stay on same filesystem)
TMP_DIR=$(dirname "$FRAG_OUT")
NS_BAM="${TMP_DIR}/${SAMPLE_ID}.namesort.bam"

# Step 1: Name-sort
echo "[STEP] name-sorting $REAL_BAM"
samtools sort -n -@ "$CPUS" -o "$NS_BAM" "$REAL_BAM"

# Step 2: Extract fragments (0-based, 4-col)
echo "[STEP] extracting fragments"
python 00_scripts/lib/bam_to_fragment.py \
    --bam "$NS_BAM" \
    --out "$FRAG_OUT" \
    --threads "$CPUS"

# Step 3: Clean up
rm -f "$NS_BAM"

# Verify output
if [ ! -f "$FRAG_OUT" ]; then
    echo "[ERROR] fragment file not created: $FRAG_OUT" >&2
    exit 1
fi

NFRAGS=$(zcat "$FRAG_OUT" | wc -l)
echo "[OK] $FRAG_OUT ($NFRAGS fragments)"
