#!/bin/bash
#SBATCH --job-name=ACR_union
#SBATCH --output=logs/ACR_union_%A_%a.out
#SBATCH --error=logs/ACR_union_%A_%a.err
#SBATCH --time=00:05:00
#SBATCH --mem=400mb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --account=YOUR_ACCOUNT_NAME
#SBATCH --partition=standard
#SBATCH --array=1-10    ## 10 chromosomes

# Union peak sets should be generated separately for each haplotype.
# For example, a B73 inbred sample contains only the B73 haplotype, whereas the BxK hybrid contains both the B73 and Ki3 haplotypes.
# Therefore BxK peak unions must be performed independently for each haplotype to generate B73-centric and Ki3-centric master ACR files.

### Note:
# Downstream ACR classification is performed within each hybrid combination, including the two parents and two reciprocal hybrids. 
# For example, the final B73-centric and Ki3-centric master ACR files for the B73 × Ki3 combination are generated by integrating peaks from B73, Ki3, BxK, and KxB.

# Convert SLURM array index (1–10) to chromosome name (chr1–chr10)
CHR="chr${SLURM_ARRAY_TASK_ID}"

# Run the Python script for this chromosome
python ./ACR_union_chr.py $CHR
